// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/3/2026, 5:37:24 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Codehub/.gemini/antigravity-ide/scratch/microfinance-system/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;